"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
var Icons = {
  navigation: [{ name: "accessibility", icon: null }, { name: "account", icon: null }, { name: "add", icon: null }, { name: "add circle", icon: null }, { name: "apps", icon: null }, { name: "arrow back", icon: null }, { name: "arrow down", icon: null }, { name: "arrow drop down", icon: null }, { name: "arrow drop down circle", icon: null }, { name: "arrow drop up", icon: null }, { name: "arrow forward", icon: null }, { name: "arrow right", icon: null }, { name: "arrow up", icon: null }, { name: "attachment", icon: null }, { name: "attach file", icon: null }, { name: "border color", icon: null }, { name: "build", icon: null }, { name: "cancel", icon: null }, { name: "check", icon: null }, { name: "check circle", icon: null }, { name: "chevron left", icon: null }, { name: "chevron right", icon: null }, { name: "close", icon: null }, { name: "clipboard", icon: null }, { name: "comment", icon: null }, { name: "contacts", icon: null }, { name: "dashboard", icon: null }, { name: "date range", icon: null }, { name: "delete", icon: null }, { name: "edit", icon: null }, { name: "email", icon: null }, { name: "exit full screen", icon: null }, { name: "expand less", icon: null }, { name: "expand more", icon: null }, { name: "filter list", icon: null }, { name: "find page", icon: null }, { name: "first page", icon: null }, { name: "flag", icon: null }, { name: "full screen", icon: null }, { name: "group", icon: null }, { name: "inbox", icon: null }, { name: "label", icon: null }, { name: "last page", icon: null }, { name: "library books", icon: null }, { name: "menu", icon: null }, { name: "merge", icon: null }, { name: "more horiz", icon: null }, { name: "more vert", icon: null }, { name: "note", icon: null }, { name: "person add", icon: null }, { name: "photo", icon: null }, { name: "photo camera", icon: null }, { name: "print", icon: null }, { name: "refresh", icon: null }, { name: "save", icon: null }, { name: "search", icon: null }, { name: "send", icon: null }, { name: "settings", icon: null }, { name: "settings application", icon: null }, { name: "shuffle", icon: null }, { name: "street view", icon: null }, { name: "sub arrow left", icon: null }, { name: "sub arrow right", icon: null }, { name: "swap horiz", icon: null }, { name: "tag", icon: null }, { name: "tags", icon: null }, { name: "transform", icon: null }, { name: "time", icon: null }, { name: "view list", icon: null }, { name: "work", icon: null }],

  editor: [{ name: "bold", icon: null }, { name: "code", icon: null }, { name: "italic", icon: null }, { name: "link", icon: null }, { name: "list numbered", icon: null }, { name: "list bulleted", icon: null }, { name: "title", icon: null }, { name: "web", icon: null }, { name: "underlined", icon: null }]
};

exports.default = Icons;
module.exports = exports['default'];